version: '3.9'
services:
  postgres:
    build:
      context: .
      dockerfile: db-image.Dockerfile
    image: 'nodejs2023q2-service-postgres'
    container_name: 'postgres'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - postgres:${PGDATA}
    networks:
      back-tier:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    ports:
      - '5432:5432'
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: app-image.Dockerfile
    image: 'nodejs2023q2-service-app'
    container_name: app
    ports:
      - '4000:4000'
    networks:
      back-tier:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11
    restart: unless-stopped
networks:
  back-tier:
    ipam:
      driver: default
      config:
        - subnet: '172.16.238.0/24'
        - subnet: '2001:3984:3989::/64'
volumes:
  postgres:
